"[build]
  base = \"frontend\"
  command = \"yarn build\"
  publish = \"build\"

[[redirects]]
  from = \"/*\"
  to = \"/index.html\"
  status = 200

[build.environment]
  NODE_VERSION = \"18\"
  YARN_VERSION = \"1.22.22\"

[[headers]]
  for = \"/*\"
  [headers.values]
    X-Frame-Options = \"DENY\"
    X-Content-Type-Options = \"nosniff\"
    Referrer-Policy = \"no-referrer\"
    
[[headers]]
  for = \"/static/*\"
  [headers.values]
    Cache-Control = \"public, max-age=31536000, immutable\"
"